### ISSUE TITLE
quic-go doesn't build on go 1.19 yet

### ISSUE THREAD

**Issue by vela-security** [andeya/erpc#101]
quic-go doesn't build on go 1.19 yet

**Comment by andeya** [comment]
get, i will fix it

**Comment by andeya** [comment]
@vela-security you can try again

**Comment by vela-security** [comment]
![image](https://user-images.githubusercontent.com/7379009/206697744-75a85dc4-2ab0-47f3-905c-7bbed2a6c26e.png)

**Comment by vela-security** [comment]
![image](https://user-images.githubusercontent.com/7379009/206697799-44dc2127-1140-4257-92e4-a1d9563ae130.png)

**Comment by andeya** [comment]
pull master codes

**Comment by vela-security** [comment]
![image](https://user-images.githubusercontent.com/7379009/206830508-1915d46c-1cfe-4fdf-acd1-bea0cf3af76c.png)

**Comment by andeya** [comment]
edit v7.0.0 to master，and then `go mod tidy`
